name: Build and Test 22

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

    

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Инсталираме .NET 6.0, защото проектът ви го изисква за изпълнение
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          
        cache: true
        cache-dependency-path: '**/*.csproj'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Execute unit tests
      run: dotnet test --configuration Release --no-restore

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          
        cache: true
        cache-dependency-path: '**/*.csproj'

    - name: Publish the application
      run: dotnet publish --configuration Release --no-restore --output ./publish

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: published-app
    
