name: Build and Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Инсталираме .NET 6.0, защото проектът ви го изисква за изпълнение
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          6.0.x
          8.0.x
          
        cache: true
        cache-dependency-path: '**/*.csproj'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build and Execute unit tests
      run: dotnet test --configuration Release --no-restore
